sudo: false

dist: bionic

language: c++

git:
  depth: 3

env:
    - CC=mpicc CXX=mpic++ FC=mpif90 FCCPP=cpp LIBSPGROOT=/home/travis/local

#before_install:

install:
    - sudo apt-get install -y gfortran mpich libmpich-dev liblapack-dev libhdf5-dev libgsl-dev libfftw3-dev libxc-dev
    - python3 prerequisite.py /home/travis/local spfft spg
    - mkdir build && cmake -S./ -B./build -DSpFFT_DIR=/home/travis/local/lib/cmake/SpFFT -DCMAKE_INSTALL_PREFIX=/home/travis/local
    - make -C./build -j 2 install

#    - sudo apt-get install -y apt-transport-https ca-certificates gnupg software-properties-common
#    - sudo wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
#    - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
#    - sudo apt-get update
#    - sudo apt-get install -y cmake
#    - sudo apt-get install -y kitware-archive-keyring
#    - sudo apt-key --keyring /etc/apt/trusted.gpg del C1F34CDD40CD72DA

branches:
  only:
    - develop

script:
  - ./check_format.x

#after_success:
#after_failure:

