sudo: false

dist: bionic

language: c++

git:
  depth: 1

before_install:

branches:
  only:
    - develop

script:
  - ls
  - pwd
  - env
  - git diff-tree
  - git show --name-only
  - git diff-tree --no-commit-id --name-only -r HEAD
  - ./check_format.x

after_success:
after_failure:

