sudo: false

language: c++

git:
  depth: 1

before_install:
 - clang --version
 - sudo apt-get update
 - sudo apt-get install python3

branches:
  only:
    - develop

script:
  - sh check_format.x

after_success:
after_failure:

