sudo: false

dist: bionic

language: c++

git:
  depth: 1

before_install:
 - clang --version
 - python --version

branches:
  only:
    - develop

script:
  - sh check_format.x

after_success:
after_failure:

